name: Secrets

on: push

jobs:
    show:
        runs-on: ubuntu-latest

        # Es un contenedor de docker (de dockerhub)
        services: 
          redis:
            image: redis
            ports:
              - 6379:6379

        steps:
            - name: Welcome
              run: |
                echo "${{secrets.APIKEY}}"